4 nodes

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -56,7 +56,228 @@ x-quorum-def:
       --unlock 0 \
       --password /examples/passwords.txt \
       $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}}
+x-tx-manager-def:
+  &tx-manager-def
+  image: "${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.7.3}"
+  expose:
+  - "9000"
+  - "9080"
+  restart: "no"
+  healthcheck:
+    test: ["CMD-SHELL", "[ -S /qdata/tm/tm.ipc ] || exit 1"]
+    interval: 3s
+    timeout: 3s
+    retries: 20
+    start_period: 5s
+  entrypoint:
+  - /bin/sh
+  - -c
+  - |
+    DDIR=/qdata/tm
+    rm -rf $${DDIR}
+    mkdir -p $${DDIR}
+    DOCKER_IMAGE="${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.7.3}"
+    TX_MANAGER=$$(echo $${DOCKER_IMAGE} | sed 's/^.*\/\(.*\):.*$$/\1/g')
+    echo "TxManager: $${TX_MANAGER}"
+    case $${TX_MANAGER}
+    in
+      tessera)
+        cp /examples/keys/tm$${NODE_ID}.pub $${DDIR}/tm.pub
+        cp /examples/keys/tm$${NODE_ID}.key $${DDIR}/tm.key
+        #extract the tessera version from the jar
+        TESSERA_VERSION=$$(unzip -p /tessera/tessera-app.jar META-INF/MANIFEST.MF | grep Tessera-Version | cut -d" " -f2)
+        echo "Tessera version (extracted from manifest file): $${TESSERA_VERSION}"
+        #we're going to do a lexicographic comparison further down so we need "0.8" to be bigger than "0.8 " - thus adding -suffix
+        TESSERA_VERSION="$${TESSERA_VERSION}-suffix"
 
+        TESSERA_CONFIG_TYPE=
+
+        #the space in "0.8 " is important in the lexicographic comparision (space is lower value than most printable chars)
+        #TODO - this will break when we get to version 0.10 (hopefully we would have moved to 1.x by then)
+        if [ "$${TESSERA_VERSION}" \> "0.8 " ]; then
+            TESSERA_CONFIG_TYPE="-enhanced"
+        fi
+
+        echo Config type $${TESSERA_CONFIG_TYPE}
+
+        #generating the two config flavors
+        cat <<EOF > $${DDIR}/tessera-config.json
+        {
+            "useWhiteList": false,
+            "jdbc": {
+                "username": "sa",
+                "password": "",
+                "url": "jdbc:h2:./$${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
+                "autoCreateTables": true
+            },
+            "server": {
+                "port": 9000,
+                "hostName": "http://$$(hostname -i)",
+                "sslConfig": {
+                    "tls": "OFF",
+                    "generateKeyStoreIfNotExisted": true,
+                    "serverKeyStore": "$${DDIR}/server-keystore",
+                    "serverKeyStorePassword": "quorum",
+                    "serverTrustStore": "$${DDIR}/server-truststore",
+                    "serverTrustStorePassword": "quorum",
+                    "serverTrustMode": "TOFU",
+                    "knownClientsFile": "$${DDIR}/knownClients",
+                    "clientKeyStore": "$${DDIR}/client-keystore",
+                    "clientKeyStorePassword": "quorum",
+                    "clientTrustStore": "$${DDIR}/client-truststore",
+                    "clientTrustStorePassword": "quorum",
+                    "clientTrustMode": "TOFU",
+                    "knownServersFile": "$${DDIR}/knownServers"
+                }
+            },
+            "peer": [
+                {
+                    "url": "http://txmanager1:9000"
+                },
+                {
+                    "url": "http://txmanager2:9000"
+                },
+                {
+                    "url": "http://txmanager3:9000"
+                },
+                {
+                    "url": "http://txmanager4:9000"
+                },
+                {
+                    "url": "http://txmanager5:9000"
+                },
+                {
+                    "url": "http://txmanager6:9000"
+                },
+                {
+                    "url": "http://txmanager7:9000"
+                }
+            ],
+            "keys": {
+                "passwords": [],
+                "keyData": [
+                    {
+                        "config": $$(cat $${DDIR}/tm.key),
+                        "publicKey": "$$(cat $${DDIR}/tm.pub)"
+                    }
+                ]
+            },
+            "alwaysSendTo": [],
+            "unixSocketFile": "$${DDIR}/tm.ipc"
+        }
+    EOF
+
+        cat <<EOF > $${DDIR}/tessera-config-enhanced.json
+        {
+          "useWhiteList": false,
+          "jdbc": {
+            "username": "sa",
+            "password": "",
+            "url": "jdbc:h2:./$${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
+            "autoCreateTables": true
+          },
+          "serverConfigs":[
+          {
+            "app":"ThirdParty",
+            "enabled": true,
+            "serverSocket":{
+              "type":"INET",
+              "port": 9080,
+              "hostName": "http://$$(hostname -i)"
+            },
+            "communicationType" : "REST"
+          },
+          {
+            "app":"Q2T",
+            "enabled": true,
+            "serverSocket":{
+              "type":"UNIX",
+              "path":"$${DDIR}/tm.ipc"
+            },
+            "communicationType" : "UNIX_SOCKET"
+          },
+          {
+            "app":"P2P",
+            "enabled": true,
+            "serverSocket":{
+              "type":"INET",
+              "port": 9000,
+              "hostName": "http://$$(hostname -i)"
+            },
+            "sslConfig": {
+              "tls": "OFF",
+              "generateKeyStoreIfNotExisted": true,
+              "serverKeyStore": "$${DDIR}/server-keystore",
+              "serverKeyStorePassword": "quorum",
+              "serverTrustStore": "$${DDIR}/server-truststore",
+              "serverTrustStorePassword": "quorum",
+              "serverTrustMode": "TOFU",
+              "knownClientsFile": "$${DDIR}/knownClients",
+              "clientKeyStore": "$${DDIR}/client-keystore",
+              "clientKeyStorePassword": "quorum",
+              "clientTrustStore": "$${DDIR}/client-truststore",
+              "clientTrustStorePassword": "quorum",
+              "clientTrustMode": "TOFU",
+              "knownServersFile": "$${DDIR}/knownServers"
+            },
+            "communicationType" : "REST"
+          }
+          ],
+          "peer": [
+             {
+                 "url": "http://txmanager1:9000"
+             },
+             {
+                 "url": "http://txmanager2:9000"
+             },
+             {
+                 "url": "http://txmanager3:9000"
+             },
+             {
+                 "url": "http://txmanager4:9000"
+             },
+             {
+                 "url": "http://txmanager5:9000"
+             },
+             {
+                 "url": "http://txmanager6:9000"
+             },
+             {
+                 "url": "http://txmanager7:9000"
+             }
+          ],
+          "keys": {
+            "passwords": [],
+            "keyData": [
+              {
+                "config": $$(cat $${DDIR}/tm.key),
+                "publicKey": "$$(cat $${DDIR}/tm.pub)"
+              }
+            ]
+          },
+          "alwaysSendTo": []
+        }
+    EOF
+
+        java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
+        ;;
+      constellation)
+        echo "socket=\"$${DDIR}/tm.ipc\"\npublickeys=[\"/examples/keys/tm$${NODE_ID}.pub\"]\n" > $${DDIR}/tm.conf
+        constellation-node \
+          --url=http://$$(hostname -i):9000/ \
+          --port=9000 \
+          --socket=$${DDIR}/tm.ipc \
+          --othernodes=http://172.16.239.101:9000/,http://172.16.239.102:9000/,http://172.16.239.103:9000/,http://172.16.239.104:9000/,http://172.16.239.105:9000/ \
+          --publickeys=/examples/keys/tm$${NODE_ID}.pub \
+          --privatekeys=/examples/keys/tm$${NODE_ID}.key \
+          --storage=$${DDIR} \
+          --verbosity=4
+        ;;
+      *)
+        echo "Invalid Transaction Manager"
+        exit 1
+        ;;
+    esac
 services:
   node1:
     << : *quorum-def
@@ -66,13 +287,25 @@ services:
     volumes:
     - 1:/qdata
     - ./examples/7nodes:/examples:ro
-
+    depends_on:
+    - txmanager1
     environment:
+    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
     - NODE_ID=1
     networks:
       quorum-examples-net:
         ipv4_address: 172.16.239.11
-
+  txmanager1:
+    << : *tx-manager-def
+    hostname: txmanager1
+    volumes:
+    - 1:/qdata
+    - ./examples/7nodes:/examples:ro
+    networks:
+      quorum-examples-net:
+        ipv4_address: 172.16.239.101
+    environment:
+    - NODE_ID=1
   node2:
     << : *quorum-def
     hostname: node2
@@ -81,13 +314,25 @@ services:
     volumes:
     - 2:/qdata
     - ./examples/7nodes:/examples:ro
-
+    depends_on:
+    - txmanager2
     environment:
+    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
     - NODE_ID=2
     networks:
       quorum-examples-net:
         ipv4_address: 172.16.239.12
-
+  txmanager2:
+    << : *tx-manager-def
+    hostname: txmanager2
+    volumes:
+    - 2:/qdata
+    - ./examples/7nodes:/examples:ro
+    networks:
+      quorum-examples-net:
+        ipv4_address: 172.16.239.102
+    environment:
+    - NODE_ID=2
   node3:
     << : *quorum-def
     hostname: node3
@@ -96,13 +341,25 @@ services:
     volumes:
     - 3:/qdata
     - ./examples/7nodes:/examples:ro
-
+    depends_on:
+    - txmanager3
     environment:
+    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
     - NODE_ID=3
     networks:
       quorum-examples-net:
         ipv4_address: 172.16.239.13
-
+  txmanager3:
+    << : *tx-manager-def
+    hostname: txmanager3
+    volumes:
+    - 3:/qdata
+    - ./examples/7nodes:/examples:ro
+    networks:
+      quorum-examples-net:
+        ipv4_address: 172.16.239.103
+    environment:
+    - NODE_ID=3
   node4:
     << : *quorum-def
     hostname: node4
@@ -111,12 +368,25 @@ services:
     volumes:
     - 4:/qdata
     - ./examples/7nodes:/examples:ro
-
+    depends_on:
+    - txmanager4
     environment:
+    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
     - NODE_ID=4
     networks:
       quorum-examples-net:
         ipv4_address: 172.16.239.14
+  txmanager4:
+    << : *tx-manager-def
+    hostname: txmanager4
+    volumes:
+    - 4:/qdata
+    - ./examples/7nodes:/examples:ro
+    networks:
+      quorum-examples-net:
+        ipv4_address: 172.16.239.104
+    environment:
+    - NODE_ID=4
 
 networks:
   quorum-examples-net:
@@ -130,3 +400,4 @@ volumes:
   "2":
   "3":
   "4":
+
